// <auto-generated />
using LWConsultantSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LWConsultantSQL.Migrations
{
    [DbContext(typeof(LWConsultantContext))]
    [Migration("20240824164231_DBLconsultant")]
    partial class DBLconsultant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("LWConsultantSQL.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("LWConsultantSQL.Keyword", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("KeywordId");

                    b.HasIndex("ItemId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("LWConsultantSQL.Keyword", b =>
                {
                    b.HasOne("LWConsultantSQL.Item", null)
                        .WithMany("Keyword")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LWConsultantSQL.Item", b =>
                {
                    b.Navigation("Keyword");
                });
#pragma warning restore 612, 618
        }
    }
}
